initScope: terenceodonoghue

nodeLinker: node-modules

npmScopes:
  terenceodonoghue:
    npmAuthToken: "${GITHUB_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
